import 'package:flutter/material.dart';
import '../models/account.dart';
import '../models/category.dart';
import '../services/account_service.dart';
import '../services/category_service.dart';
import '../widgets/account_card.dart';
import '../widgets/account_form_dialog.dart';
import '../widgets/category_dialog.dart';
import '../widgets/delete_confirm_dialog.dart';
class CategoryDetailScreen extends StatefulWidget {final Category category;const CategoryDetailScreen({super.key,required this.category});@override State<CategoryDetailScreen> createState() => _CategoryDetailScreenState();}class _CategoryDetailScreenState extends State<CategoryDetailScreen> {final AccountService _accountService = AccountService();final CategoryService _categoryService = CategoryService();List<Account> _accounts = [];List<Category> _subCategories = [];bool _isLoading = true;Category get _cat => widget.category;@override void initState() { super.initState(); _loadData(); }Future<void> _loadData() async {setState(() => _isLoading = true);try {final accounts = await _accountService.getAccountsByCategory(categoryId: _cat.id!);final subs = await _categoryService.getSubCategories(parentId: _cat.id!);setState(() { _accounts = accounts; _subCategories = subs; _isLoading = false; });} catch (e) {setState(() => _isLoading = false);if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));}}Future<void> _showMoveAccountDialog(Account account) async {final allCats = await _categoryService.getAllCategories();final targets = allCats.where((c) => c.id != _cat.id).toList();if (targets.isEmpty) {if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Khong co thu muc nao khac de di chuyen')));return;}final choice = await showDialog<Category>(context: context, builder: (ctx) => SimpleDialog(title: const Text('Chon thu muc'), children: targets.map((c) => SimpleDialogOption(onPressed: () => Navigator.of(ctx).pop(c), child: Text(c.name))).toList()));if (choice != null) { await _accountService.moveAccount(id: account.id!, newCategoryId: choice.id!); _loadData(); }}