name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subesh/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'
      - run: flutter pub get
      - name: Fix Android SDK & Generate Icons
        run: |
          # Fix Android SDK version to 35
          sed -i 's/compileSdkVersion = flutter.compileSdkVersion/compileSdk = 35/g' android/app/build.gradle
          sed -i 's/targetSdkVersion = flutter.targetSdkVersion/targetSdk = 35/g' android/app/build.gradle
          # Generate launcher icons
          flutter create --template=app --project-name=tmp_icon /tmp/tmp_icon
          cp /rmp/tmp_icon/android/app/src/main/res/mipmap-*/ic_launcher.png android/app/src/main/res/mipmap-*/
          rm -rf /tmp/tmp_icon
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk